# Generated by Django 3.2.8 on 2021-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Organizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpieza_val', models.CharField(choices=[('MB', 'Muy Bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy Mal')], default='MB', max_length=50)),
                ('sac_polvo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='MB', max_length=50)),
                ('limpieza_bannos', models.CharField(choices=[('MB', 'Muy Bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy Mal')], default='MB', max_length=50)),
                ('servicio_limpieza', models.CharField(choices=[('MB', 'Muy Bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy Mal')], default='MB', max_length=50)),
            ],
        ),
    ]
