# Generated by Django 3.2.8 on 2021-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_encuesta_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='area',
            field=models.CharField(choices=[('DT', 'Direccion Territorial'), ('CTA', 'Centro de Telecomunicaciones Artemisa'), ('T', 'Telepunto'), ('TT', 'Taller de Telefonos'), ('ALSC', 'Area de Logistica y Servicios Chalet'), ('UO', 'Unidad Operativa')], max_length=50),
        ),
    ]
