# Generated by Django 3.2.8 on 2021-11-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_alter_encuesta_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area_Organizativa',
        ),
    ]
