# Generated by Django 3.2.8 on 2021-11-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_delete_area_organizativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Organizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.area_organizativa'),
        ),
    ]
