# Generated by Django 3.2.8 on 2021-11-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_auto_20211109_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
