# Generated by Django 3.2.8 on 2021-11-12 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuesta', '0006_encuesta_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
