# Generated by Django 3.2.8 on 2021-11-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_encuesta_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='user_id',
        ),
    ]
